{
 "title": "Dual Robot Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total Requests Per second (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(\n  flask_http_request_duration_seconds_count[30s]\n)"
    }
   ]
  },
  {
   "title": "Jaeger Spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "operation": "torvalds-eye", "service": "stop-service" }
   ]
  },
  {
   "title": "Average Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(\n  flask_http_request_duration_seconds_sum{status=\"200\"}[30s]\n)\n /\nrate(\n  flask_http_request_duration_seconds_count{status=\"200\"}[30s]\n)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"dualrobot-cncf\"}"
    }
   ]
  },
  {
   "title": "Pod Uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{container=~\"dualrobot-cncf\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Requests Per Second (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(\n  flask_http_request_duration_seconds_count{status=\"200\"}[30s]\n)\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(\n  process_cpu_seconds_total{job=\"dualrobot-cncf\"}[30s]\n)"
    }
   ]
  }
 ]
}